apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  type: NodePort
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 80          # クラスター内で公開するポート
      targetPort: 3000  # Pod のポート
      nodePort: 30080   # 外部に公開するポート (任意の範囲: 30000～32767)
