apiVersion: v1
kind: Pod
metadata:
  name: node-app
  labels:
    app: node-app
spec:
  containers:
    - name: node-container
      image: node:18-slim
      command: ["node", "-e", "require('http').createServer((req, res) => { res.end('Hello from Node'); }).listen(3000)"]
      ports:
        - containerPort: 3000
