services:
  go_tutorial_2025_1226:
    build:
      context: .
      dockerfile: Dockerfile
    image: go_tutorial_2025_1226
    user: "1000:1000"
    container_name: go_tutorial_2025_1226
    volumes:
      - ../app:/app
      - go_cache:/go

    tty: true
    stdin_open: true
    command: ["tail", "-f", "/dev/null"]

volumes:
  go_cache:
