services:
  searxng:
    image: searxng/searxng
    container_name: searxng
    ports:
      - "8080:8080"
    volumes:
      - ./searxng:/etc/searxng
    environment:
      - BASE_URL=http://127.0.0.1:8080/
      - INSTANCE_NAME=my-searxng-instance
    restart: unless-stopped

