services:
  rn:
    build: .
    container_name: rn-dev
    volumes:
      - ./app:/app
    working_dir: /app
    ports:
      - "8081:8081"  # Metro bundler用
      - "19000:19000"  # Expo Go用
      - "19001:19001"  # Web用
      - "19002:19002"  # 開発者ツール
    stdin_open: true
    tty: true
    network_mode: "host"  # スマホでアクセスする場合など
