services:
  redis:
    image: redis:8.2.1
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command:
      - redis-server
      - "--appendonly"
      - "yes"

    redisinsight:
      image: redis/redisinsight:2.70.1
      container_name: redisinsight
      ports:
        - "5540:5540"
      depends_on:
        - redis
volumes:
  redis_data

    
        

